<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://netservice-convert-pdf-to-html-v1.p.mashape.com/api/documents/pdf2html.json");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "X-Mashape-Key: In6SBZF6oJmshwk3zDfm0kWTzvVkp11hzE3jsntXMDKRReTK0U";
$headers[] = "X-Blackboxapiid: 3";
$headers[] = "X-Blackboxapitoken: Mashape";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

?>